#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM alpine:3.16.0

RUN apk add geth
RUN apk add nano
RUN apk add jq

ENTRYPOINT /bin/sh

