version: "3.9"
services:
    va-mongodb: #https://hub.docker.com/_/mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: voting-authority
    
    va-frontend:
        ports:
            - 3000:3000
        environment:
            - REACT_APP_VA_BACKEND="http://localhost:5000"
        build:
            context: ../voting-authority/frontend
            dockerfile: ./Dockerfile
        depends_on:
            - va-backend
    
    va-backend:
        ports:
            - 5000:5000
            - 8545:8545
            - 8546:8546
            - 30300:30300
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - MongoDbConnectionString=mongodb://root:voting-authority@host.docker.internal:27017
            - BC_ACCOUNT_PWD=test3
            - PORT=30300
            - IpfsHost=http://host.docker.internal:5001
            - GethEndpoint=http://localhost:8545
        volumes:
            - ./va:/home
        build:
            context: ../voting-authority/backend/
            dockerfile: Helverify.VotingAuthority.Backend/Dockerfile    
        links:
            - va-mongodb
            - consensus-backend1
            - consensus-backend2
        depends_on:
            - va-mongodb
    
    voter-frontend:
        ports:
            - 3001:3000
        environment:
            - REACT_APP_IPFS_URL="http://localhost:8080/ipfs"
            - REACT_APP_GETH_WS="ws://localhost:8546"
        build:
            context: ../voter/frontend
            dockerfile: ./Dockerfile
        depends_on:
            - va-backend # because of RPC endpoint
            - ipfs-node1 # because of IPFS endpoint
    
    consensus-backend1:
        ports:
            - 5002:5000
            - 30301:30301
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test1
            - PORT=30301
            - IpfsHost=http://host.docker.internal:5001
        volumes: 
            - ./consensus1:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
            
    consensus-backend2:
        ports:
            - 5003:5000
            - 30302:30302
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test2
            - PORT=30302
            - IpfsHost=http://host.docker.internal:5001
        volumes: 
            - ./consensus2:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    
    consensus-backend3:
        ports:
            - 5004:5000
            - 30303:30303
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test3
            - PORT=30303
            - IpfsHost=http://host.docker.internal:5001
        volumes: 
            - ./consensus3:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
            
    #consensus-backend4:
    #    ports:
    #        - 5005:5000
    #        - 30304:30304
    #    environment: 
    #        - ASPNETCORE_URLS=http://+:5000
    #        - BC_ACCOUNT_PWD=test4
    #        - PORT=30304
    #        - IpfsHost=http://host.docker.internal:5001
    #    volumes: 
    #        - ./consensus4:/home/
    #    build:
    #        context: ../consensus-node/backend/
    #        dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    #consensus-backend5:
    #    ports:
    #        - 5006:5000
    #        - 30305:30305
    #    environment: 
    #        - ASPNETCORE_URLS=http://+:5000
    #        - BC_ACCOUNT_PWD=test5
    #        - PORT=30305
    #        - IpfsHost=http://host.docker.internal:5001
    #    volumes: 
    #        - ./consensus5:/home/
    #    build:
    #        context: ../consensus-node/backend/
    #        dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    #consensus-backend6:
    #    ports:
    #        - 5007:5000
    #        - 30306:30306
    #    environment: 
    #        - ASPNETCORE_URLS=http://+:5000
    #        - BC_ACCOUNT_PWD=test6
    #        - PORT=30306
    #        - IpfsHost=http://host.docker.internal:5001
    #    volumes: 
    #        - ./consensus6:/home/
    #    build:
    #        context: ../consensus-node/backend/
    #        dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    #consensus-backend7:
    #    ports:
    #        - 5008:5000
    #        - 30307:30307
    #    environment: 
    #        - ASPNETCORE_URLS=http://+:5000
    #        - BC_ACCOUNT_PWD=test7
    #        - PORT=30307
    #        - IpfsHost=http://host.docker.internal:5001
    #    volumes: 
    #        - ./consensus7:/home/
    #    build:
    #        context: ../consensus-node/backend/
    #        dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    #consensus-backend8:
    #    ports:
    #        - 5009:5000
    #        - 30308:30308
    #    environment: 
    #        - ASPNETCORE_URLS=http://+:5000
    #        - BC_ACCOUNT_PWD=test8
    #        - PORT=30308
    #        - IpfsHost=http://host.docker.internal:5001
    #    volumes: 
    #        - ./consensus8:/home/
    #    build:
    #        context: ../consensus-node/backend/
    #        dockerfile: Helverify.ConsensusNode.Backend/Dockerfile        
    
    ipfs-node1:
        image: ipfs/go-ipfs
        volumes: 
            - ./ipfs1/export:/export
            - ./ipfs1/data:/data
            - ./ipfs1/home:/home/ipfs
        environment: 
            - ipfs_staging=/export
            - ipfs_data=/data
            - IPFS_SWARM_KEY_FILE=/home/ipfs/swarm.key
        ports:
            - 4001:4001
            - 5001:5001
            - 8080:8080

    ipfs-node2:
        image: ipfs/go-ipfs
        volumes: 
            - ./ipfs2/export:/export
            - ./ipfs2/data:/data
            - ./ipfs2/home:/home/ipfs
        environment: 
            - ipfs_staging=/export
            - ipfs_data=/data
            - IPFS_SWARM_KEY_FILE=/home/ipfs/swarm.key
        ports:
            - 4002:4001
            
    ipfs-node3:
        image: ipfs/go-ipfs
        volumes: 
            - ./ipfs3/export:/export
            - ./ipfs3/data:/data
            - ./ipfs3/home:/home/ipfs
        environment: 
            - ipfs_staging=/export
            - ipfs_data=/data
            - IPFS_SWARM_KEY_FILE=/home/ipfs/swarm.key
        ports:
            - 4003:4001
                    
# BC Configuration according to: 
#  https://medium.com/coinmonks/private-ethereum-by-example-b77063bb634f
#  https://geth.ethereum.org/docs/interface/private-network
#  https://geth.ethereum.org/docs/rpc/server
#  https://docs.ipfs.io/how-to/run-ipfs-inside-docker/#private-swarms-inside-docker
# IPFS:
#  swarm key generation: https://discuss.ipfs.io/t/private-ipfs-network/12441/3
#  environment variables: https://github.com/ipfs/go-ipfs/blob/master/docs/environment-variables.md