version: "3.9"
services:
    va-mongodb: #https://hub.docker.com/_/mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: voting-authority
    
    va-backend:
        ports:
            - 5001:5000
            - 8545:8545
            - 30300:30300
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - MongoDbConnectionString=mongodb://root:voting-authority@host.docker.internal:27017
            - BC_ACCOUNT_PWD=test3
            - PORT=30304
        build:
            context: ../voting-authority/backend/
            dockerfile: Helverify.VotingAuthority.Backend/Dockerfile    
        links:
            - va-mongodb
            - consensus-backend1
            - consensus-backend2
        depends_on:
            - va-mongodb
    
    consensus-backend1:
        ports:
            - 5002:5000
            - 30301:30301
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test1
            - PORT=30301
        volumes: 
            - ./consensus1:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
            
    consensus-backend2:
        ports:
            - 5003:5000
            - 30302:30302
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test2
            - PORT=30302
        volumes: 
            - ./consensus2:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
    
    consensus-backend3:
        ports:
            - 5004:5000
            - 30303:30303
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test3
            - PORT=30303
        volumes: 
            - ./consensus3:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
            
    consensus-backend4:
        ports:
            - 5005:5000
            - 30304:30304
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - BC_ACCOUNT_PWD=test4
            - PORT=30304
        volumes: 
            - ./consensus4:/home/
        build:
            context: ../consensus-node/backend/
            dockerfile: Helverify.ConsensusNode.Backend/Dockerfile
                    
# BC Configuration according to: 
#  https://medium.com/coinmonks/private-ethereum-by-example-b77063bb634f
#  https://geth.ethereum.org/docs/interface/private-network
#  https://geth.ethereum.org/docs/rpc/server