version: "3.9"
services:
    va-mongodb: #https://hub.docker.com/_/mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: voting-authority